import './globals.css'
import { Inter } from 'next/font/google';
import { Navbar } from '@/components';
import { Footer } from '@/containers';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='container m-auto'>
        <header>
          <Navbar />
        </header>
        <main>
          <div>
            {children}
          </div>
        </main>
        <footer>
          <Footer/>
        </footer>
      </body>
    </html>
  )
}
